// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXpxnaGxVIBQ9hS4-3ZpMBNf4loI1o0JM',
    appId: '1:249940285521:web:8b3be6cf1f68fbbe5cc070',
    messagingSenderId: '249940285521',
    projectId: 'gdsc-flutter-course',
    authDomain: 'gdsc-flutter-course.firebaseapp.com',
    storageBucket: 'gdsc-flutter-course.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOPi-Kpm6bJXayjO7Fl9DwBvtq58Hrl_k',
    appId: '1:249940285521:android:1729b9af07fc8bad5cc070',
    messagingSenderId: '249940285521',
    projectId: 'gdsc-flutter-course',
    storageBucket: 'gdsc-flutter-course.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlEK3nj_Nt60bv8o9Wzgd0ATxE7acP7ow',
    appId: '1:249940285521:ios:494f384375bfe9d45cc070',
    messagingSenderId: '249940285521',
    projectId: 'gdsc-flutter-course',
    storageBucket: 'gdsc-flutter-course.appspot.com',
    iosClientId: '249940285521-e4k94dmovuk006l5icelkmlt1t730005.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdscFlutterCourseSession9CloudFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlEK3nj_Nt60bv8o9Wzgd0ATxE7acP7ow',
    appId: '1:249940285521:ios:c7d17471f2c5b81d5cc070',
    messagingSenderId: '249940285521',
    projectId: 'gdsc-flutter-course',
    storageBucket: 'gdsc-flutter-course.appspot.com',
    iosClientId: '249940285521-rg4ohaj28jlk5nqihtvhhv28aavpjt6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdscFlutterCourseSession9CloudFirestore.RunnerTests',
  );
}
